### ISSUE TITLE
Change System options 

### ISSUE THREAD

**Issue by miggi92** [AlexandrErohin/home-assistant-flightradar24#1]
It would be nice if in the future we could change the system options like:
- refresh rate 
- radius 

Example:
![Screenshot_20231124-100704.png](https://github.com/AlexandrErohin/home-assistant-flightradar24/assets/9019692/7d63c4b4-ffe7-4a68-9095-063749d56ea3)

**Comment by AlexandrErohin** [comment]
@miggi92 Thanks
It's in my plan list :)

**Comment by AlexandrErohin** [comment]
@miggi92 Added
