### ISSUE TITLE
Feature Request: altitude limit

### ISSUE THREAD

**Issue by GpsM2** [AlexandrErohin/home-assistant-flightradar24#12]
Many thanks for the great integration! As I live near an airport, it would be great to be able to specify an altitude limit, as I'm usually only interested in the planes arriving and departing. The overflights at higher altitudes are less interesting.

Thanks again!

**Comment by AlexandrErohin** [comment]
Hi, you always may do this when you display flights in Lovelace card - add IF clause and check a flight for your criteria to have it in the list. Also you may do it for notifications.
There are lot of criterias to filter flights - adding all of them will make configuring a bit sophisticated

**Comment by GpsM2** [comment]
Thank you for the fast answer! I added the IF clause as suggested:

    
```
{% if flight.altitude is defined and flight.altitude < 9000 %}

{% endif %}
```
