### ISSUE TITLE
Feature Request: estimated times

### ISSUE THREAD

**Issue by 16-9** [AlexandrErohin/home-assistant-flightradar24#13]
Alexander,

Would you consider exposing the estimated departure and arrival times of a flight as well? That information is made available by Flightradar24 as well. It would allow me to track a plane's arrival and inform me when it is time for me to leave to pick someone up at the airport.

Thanks,

Christophe

**Comment by AlexandrErohin** [comment]
Added

**Comment by AlexandrErohin** [comment]
@16-9 Dont forget please to give a star to the repo :)
