### ISSUE TITLE
Feature request: Planes on the ground

### ISSUE THREAD

**Issue by dront242** [AlexandrErohin/home-assistant-flightradar24#14]
Great integration! 👍🏻
I'd just want the option to show what's on the ground in a specific area. I live right by an airport and as soon as the planes land they "disappear" from HA.
/ David

**Comment by AlexandrErohin** [comment]
I have tested for area near an airport. Integration shows all planes on the ground and in the sky. Planes on the ground has Altitude = 0. Maybe the radius that you use in the integration ends on runway and plane parked area is more further. Airports usually very large
Try to increase radius

**Comment by sj3fk3** [comment]
Pretty sure it shows all the planes (and vehicles) on the ground, I purposely filter them out (only 15Km away from EHAM).

**Comment by AlexandrErohin** [comment]
You may always filter them when you show flight table https://github.com/AlexandrErohin/home-assistant-flightradar24?tab=readme-ov-file#lovelace-card

There are a lot of criterias to filtering and sorting. Adding all of them would make this integration sophisticated to use

**Comment by dront242** [comment]
Ok! I'll do some digging! 🙂 But, having done some quick test, it really seems like the planes are disappearing from the area when landing. I've double checked the area setting but still the same. I can see the planes in the Flight radar app on the ground, but not in HA. We can regard this issue as solved and I'll get back if I find out whats wrong for me.

**Comment by dront242** [comment]
I've done some more testing and the only thing I can think about to cause the error is that Flightradar might have a blind spot on the airport in question. For example, all flights are being showed as passing the airport when they've actually landed (which means their positions might not be updated when the planes comes near the ground). And the altitude never report anything less than ~170m.
