### ISSUE TITLE
Vertical Speed

### ISSUE THREAD

**Issue by heavyD55** [AlexandrErohin/home-assistant-flightradar24#15]
Love this integration. I have a few automations for airplanes and airliners flying overhead and announcing them on my Alexa. 

I was wondering if VSI rate could become an available 'field'. I would use this info to assist in determining whether an aircraft/airliner was inbound, outbound or cruising overhead or into/out of my nearby airport.

Thanks so much for this fun integration!

**Comment by sj3fk3** [comment]
VSI is only available if you have a premium flightradar24 account: https://www.flightradar24.com/premium

**Comment by heavyD55** [comment]
Ah I see that now. Looks like Silver or better.

Already available. Sounds good.

Thanks for the info!

**Comment by AlexandrErohin** [comment]
Added
