### ISSUE TITLE
Feature request: Higher quality photo

### ISSUE THREAD

**Issue by ajakubek80** [AlexandrErohin/home-assistant-flightradar24#16]
Thank you for the wonderful integration. 
Is it possible to add entities or replace the airplane photo with higher resolution? 
Currently, it's at 200, and 400 already looks better. 
For example:
https://cdn.jetphotos.com/200/6/1304689_1704126566_tb.jpg
https://cdn.jetphotos.com/400/6/1304689_1704126566.jpg

**Comment by AlexandrErohin** [comment]
Added aircraft_photo_medium and aircraft_photo_large

**Comment by AlexandrErohin** [comment]
@ajakubek80 Dont forget please to give a star to the repo :)
