### ISSUE TITLE
Request: Ability to hide the FlightRadar and Google / Apple 'icons' in the radar iframe.

### ISSUE THREAD

**Issue by MrMxyzptlk** [AlexandrErohin/home-assistant-flightradar24#19]
Love this! Thanking for taking the time to make this integration.

I have a FlightRadar24 'silver' account which removes adds; is there a way to remove the FlightRadar24 and Google / Apple logos from the iframe radar?

Thank you once again.

**Comment by motoridersd** [comment]
I was able to remove them with uBlock, add the lines below to your filters:

||www.flightradar24.com/static/images/apps/app_store.svg
||www.flightradar24.com/static/images/apps/google_play.svg

The iframe used to display the map doesn't have any advanced functionality that I can tell, and we are using a version of the website provided by FlightRadar that includes these images by default. Without cosmetic filtering through something like uBlock, I don't think they can be removed.

**Comment by MrMxyzptlk** [comment]
That did the trick; I also switch from AdBlock Pro to uBlock.

Thank you.

**Comment by motoridersd** [comment]
I was having issues with uBlock finding the logo, but finally figured it out. This is the full uBlock config to remove app and Fligtradar logos:

```
||www.flightradar24.com/static/images/apps/app_store.svg
||www.flightradar24.com/static/images/apps/google_play.svg
www.flightradar24.com##.logo-fr24-flat
```

**Comment by MrMxyzptlk** [comment]
Thanks!

**Comment by xbmcnut** [comment]
Any idea on how to code that to work with [Adguard Home](https://adguard.com/kb/general/ad-filtering/create-own-filters/) as that is above my pay grade 😁

**Comment by xbmcnut** [comment]
> I was having issues with uBlock finding the logo, but finally figured it out. This is the full uBlock config to remove app and Fligtradar logos:
> 
> ```
> ||www.flightradar24.com/static/images/apps/app_store.svg
> ||www.flightradar24.com/static/images/apps/google_play.svg
> www.flightradar24.com##.logo-fr24-flat
> ```

Any idea on how to code that to work with [Adguard Home](https://adguard.com/kb/general/ad-filtering/create-own-filters/) as that is above my pay grade 😁

**Comment by motoridersd** [comment]
> > I was having issues with uBlock finding the logo, but finally figured it out. This is the full uBlock config to remove app and Fligtradar logos:
> > ```
> > ||www.flightradar24.com/static/images/apps/app_store.svg
> > ||www.flightradar24.com/static/images/apps/google_play.svg
> > www.flightradar24.com##.logo-fr24-flat
> > ```
> 
> Any idea on how to code that to work with [Adguard Home](https://adguard.com/kb/general/ad-filtering/create-own-filters/) as that is above my pay grade 😁

You can't do it with AdGuard Home because they're part of the same flightradar24 domain. Only a browser extension that blocks specific elements or can manipulate the code of the page will work here.

**Comment by xbmcnut** [comment]
@motoridersd That'll be why it's not working. Thanks for the advice. Much appreciated.
