### ISSUE TITLE
Is it possible to identify which device triggered the event?

### ISSUE THREAD

**Issue by igorsantos07** [AlexandrErohin/home-assistant-flightradar24#21]
This was mentioned in #11, but since it's just tangentially related, I'm posting a separate issue: the problem is exactly what was mentioned there, there's no way to identify which place triggered the event. It would be helpful to create more meaningful notifications, for instance.

In the meantime, I'll try checking about moving the automation out of events and maybe post here an example.

**Comment by motoridersd** [comment]
What are you trying to do? If you have more than one entry of the integration, with different areas/radii, you get 3 sensors for each.

**Comment by igorsantos07** [comment]
Use the [example from the docs](https://github.com/AlexandrErohin/home-assistant-flightradar24?tab=readme-ov-file#notification).

[This other person said the same thing](https://github.com/AlexandrErohin/home-assistant-flightradar24/issues/11#issuecomment-1894354032).

**Comment by AlexandrErohin** [comment]
Added tracked_by_device to events to know what device has fired the event
