### ISSUE TITLE
Follow a particular plane

### ISSUE THREAD

**Issue by renaatdb** [AlexandrErohin/home-assistant-flightradar24#23]
Is it possible to track a specific aircraft depending on its registration number?

**Comment by AlexandrErohin** [comment]
Hi. It is under development

**Comment by AlexandrErohin** [comment]
@renaatdb Added tracking a particular plane or planes by aircraft registration number outside your area

**Comment by renaatdb** [comment]
> @renaatdb Added tracking a particular plane or planes by aircraft registration number outside your area
fantastic, thank you...

**Comment by AlexandrErohin** [comment]
@renaatdb Dont forget please to give a star to the repo :)
