### ISSUE TITLE
Unable to track specific flight by number

### ISSUE THREAD

**Issue by DevRedOWL** [AlexandrErohin/home-assistant-flightradar24#25]
![Screenshot_20240312_073520_Home Assistant](https://github.com/AlexandrErohin/home-assistant-flightradar24/assets/22500953/c6b3ad37-6984-4e95-b907-d663f2bd0463)

Hi, i was trying to track a flight and there are no way it can be added. FYI: no credentials for flightradar account are set.

UPD: I've even tried to use in different name variants, such as su1395, SU1395, SU 1395 and SU-1395.

**Comment by AlexandrErohin** [comment]
Hi, You use flight number. Integration supports tracking by aircraft registration number

**Comment by DevRedOWL** [comment]
Oh i think i missunderstood docs then, sorry for confusing.
Would flight number tracking be available? I think it would be handful to have terminal data / state like boarding or reg / flight start time / ETA.
If so, or if you already working on it - could you please send a branch, i could probably assist there.

**Comment by AlexandrErohin** [comment]
@DevRedOWL Added additional tracking by flight number and call sign

**Comment by DevRedOWL** [comment]
> @DevRedOWL Added additional tracking by flight number and call sign

Thanks! Will test)

**Comment by AlexandrErohin** [comment]
It tracks only live flights. Recent or scheduled flights are not tracked

**Comment by DevRedOWL** [comment]
> It tracks only live flights. Recent or scheduled flights are not tracked

Okay, that's interesting. But what if it will allow to track current/nearest scheduled flight?
Because i assume it would be useful for people to use it during for travel.

**Comment by donserdal** [comment]
Would be nice, but I dont think flightradar supports it. It does however support bookmarks, is there any thing we could do with that? It auto starts tracking when plane departs

**Comment by AlexandrErohin** [comment]
@donserdal @miggi92 @DevRedOWL Added tracking scheduled flights

**Comment by Manbearpig92** [comment]
> @donserdal @miggi92 @DevRedOWL Added tracking scheduled flights

how do you get this to work? does it only allow tracking on scheduled flights from the airport you configured and its monitoring? I tried to just enter a flight number that will be arriving to the airport i set up in the config and even that doesnt update the additional tracked. I also tried to add a flight number that will be scheduled to depart from the configured airport and that didnt update the additonal tracked either

**Comment by DevRedOWL** [comment]
> @donserdal @miggi92 @DevRedOWL Added tracking scheduled flights

Amazing news! Will check with the latest verion!
Спасибки

**Comment by AlexandrErohin** [comment]
@donserdal @miggi92 @DevRedOWL Dont forget please to give a star to the repo :)

**Comment by donserdal** [comment]
Started! Thanks!
