### ISSUE TITLE
No data after update beyond 1.7 and min/max wording confusing

### ISSUE THREAD

**Issue by xbmcnut** [AlexandrErohin/home-assistant-flightradar24#26]
Thank you for this awesome add-on! I'm not seeing any flights with the parameters shown below. It was working just fine under 1.6. Running 1.8 now and downgraded to 1.7, made no difference.

Also, I think the wording could be improved for the minimum and maximum heights?

- "The maximum attitude in foots above which the aircraft Will be tracked" should maybe say "Aircraft above this altitude will be ignored. (or have I got that backwards?)
- "The minimum altitude in foots under which the aircraft will be tracked" should maybe say "Aircraft below this altitude will be ignored"

Of course, upper level altitude setting should also be on top of the lower limit but that might be my OCD? 😁Using _minimum_ and _under_ together along with _maximum_ and _over_ at least for me is very confusing.

![image](https://github.com/AlexandrErohin/home-assistant-flightradar24/assets/1492137/304c1943-abef-4758-8d79-8f602e3450c4)

![image](https://github.com/AlexandrErohin/home-assistant-flightradar24/assets/1492137/40e11354-4deb-40d6-97fd-aca9bbe5c13f)
Above was with 2 aircraft in range.

**Comment by AlexandrErohin** [comment]
@xbmcnut Do you use Adguard with rule for flightradar24? https://github.com/AlexandrErohin/home-assistant-flightradar24/issues/19  Try to delete this rule.

**Comment by xbmcnut** [comment]
@AlexandrErohin Good spotting!!! 🤦‍♂️I'm a dumb arse. My broken custom filter is obviously blocking the whole domain. Removed and waiting for a plane now. Still find the wording for the min/max heights very confusing. What do you think about my suggestion? 😃

**Comment by xbmcnut** [comment]
Yes, dumb arse status confirmed. Working again now 🤗

**Comment by AlexandrErohin** [comment]
Glad you have fixed this!
