### ISSUE TITLE
Event for plane landing

### ISSUE THREAD

**Issue by User8395** [AlexandrErohin/home-assistant-flightradar24#29]
Can there be an automation that calls the notification service when a tracked flight lands?

**Comment by AlexandrErohin** [comment]
Im planning to add this in the next releases

**Comment by AlexandrErohin** [comment]
@User8395 New events are added

**Comment by User8395** [comment]
Thank you

**Comment by AlexandrErohin** [comment]
@User8395 Dont forget please to give a star to the repo :)

**Comment by User8395** [comment]
I will
