### ISSUE TITLE
Wrong flight number

### ISSUE THREAD

**Issue by User8395** [AlexandrErohin/home-assistant-flightradar24#31]
Adding TK2 (Turkish New York JFK -> Istanbul IST) to track instead adds TK20 (Turkish Istanbul IST -> Seoul ICN)

**Comment by AlexandrErohin** [comment]
@User8395 was TK2 current flight? or it was a scheduled flight?

**Comment by User8395** [comment]
It was a flight that had not yet taken off

**Comment by AlexandrErohin** [comment]
@User8395 Fixed
