### ISSUE TITLE
Minor setup wording corrections

### ISSUE THREAD

**Issue by LoznOz** [AlexandrErohin/home-assistant-flightradar24#32]
Hi
Thanks for your work on this integration, I've just installed it, so far impressed.
When installing I noticed some wording which looks incorrect (possibly just a language translation error) so constructively sharing fyi:
I'll send a picture as much easier to see & consider. 
Cheers
![image](https://github.com/AlexandrErohin/home-assistant-flightradar24/assets/119017698/1294e85c-5d54-4e71-8ddd-f6bcf13422ea)

**Comment by AlexandrErohin** [comment]
Hi!
So the first one would be - The minimum altitude in feet above the aircraft will be tracked.
The second one - The maximum altitude in feet below the aircraft will be tracked.

Right?

**Comment by LoznOz** [comment]
Yes that's correct. Even clearer wording with hindsight perhaps should be:

first one - "The minimum altitude in feet above which the aircraft will be tracked."

The second one - "The maximum altitude in feet below which the aircraft will be tracked."

**Comment by AlexandrErohin** [comment]
@LoznOz Thank you! I have fixed it.
Would be great if you could give a star to the repo :) Thanks

**Comment by LoznOz** [comment]
Thanks for fixing and reaching out. Sure if I haven't already I sure will. 👍

**Comment by RedNo7** [comment]
Is the altitude AMSL or AGL (I'm assuming) AMSL?  Can you please also show this in the description to avoid confusion?
