### ISSUE TITLE
Flight tracking - timeout "issue"?

### ISSUE THREAD

**Issue by MCBIII** [AlexandrErohin/home-assistant-flightradar24#33]
Hi 

When tracking specific planes, it seems they only get tracked foor x amount of time, cant find any doc on this. 
is this the case or? 

As of now i have to use a script to update the add to track to have them be tracked the whole flight. 

any workaraound or just a feature ?

**Comment by AlexandrErohin** [comment]
Hi
A plane tracked before his landing
