### ISSUE TITLE
New sensor - Total flights

### ISSUE THREAD

**Issue by cvc90** [AlexandrErohin/home-assistant-flightradar24#36]
Hi! @AlexandrErohin ,

Would it be possible to add a new sensor to know how many total flights the sensor "sensor.flightradar24_entered_area" records in a day?

**Comment by AlexandrErohin** [comment]
@cvc90 Hi,
You may add a statistics sensor for a specific period (15 minutes, day, week, month, year or ect.) by your own.
Here the example how to add it https://community.home-assistant.io/t/custom-component-flightradar24/641969/97

**Comment by cvc90** [comment]
Thanks, I'll try the added examples.
