### ISSUE TITLE
Feature request - Follow tracked plane on map

### ISSUE THREAD

**Issue by poudenes** [AlexandrErohin/home-assistant-flightradar24#42]
Hi There,

Would be nice to have the option to follow a tracked plane on a MAP card.
Then you can follow it like you're in the plane :)

**Comment by AlexandrErohin** [comment]
Hi!
You may add a link to a flight to flightradar in Lovelace card. And when you want to see map with the flight  - click on the link and the flightradar map with the flight will be opened.
