### ISSUE TITLE
Addon breaching FR24's Terms of Service?

### ISSUE THREAD

**Issue by sammckenzie236** [AlexandrErohin/home-assistant-flightradar24#45]
I had been running this addon for a few weeks when randomly it stopped being able to update flight information, and I also found that all of my iOS devices on the network were semi-banned from the iOS app, only displaying limited information, and overall a pretty broken app.

I reached out to Flightradar24 help and after a few back-and-forth emails they told me that this integration violates their terms of service and that the ban had been administered correctly:
_"Please note the information you describe is against Flightradar24's terms of service https://www.flightradar24.com/terms-and-conditions. So the block was correctly administered. "_

The support rep also stated that there is a new API service being released in the coming months:
_"If you require more data then you may be interested in our API service that we will be releasing shortly. Please keep an eye out for this in the coming months."_

Posting this here to see if anyone else has had the same problem, and if the developers of this addon can resolve the issue with Flightradar24. I'm still working on getting them to remove my ban but as of when I post this that is still in place.

**Comment by ginlik1996** [comment]
Are you still facing this issue?
I'm looking forward to adding this integration to my HA, but I don't want my IP to be banned.
Thanks!

**Comment by sammckenzie236** [comment]
> Are you still facing this issue? I'm looking forward to adding this integration to my HA, but I don't want my IP to be banned. Thanks!

Hi, yes absolutely I’m still in contact with support about trying to get unbanned, latest update is that “unfortunately you accepted the terms and conditions of our service (FR24) so the ban was correctly administered”. It’s a great integration but this whole IP banning thing isn’t great. I’ll update if I manage to get them to unblock me.

**Comment by AlexandrErohin** [comment]
@sammckenzie236 It is really strange. Maybe you have made a lot requests to FR24 from one IP from all of your devices at same time?
This integration based on https://github.com/JeanExtreme002/FlightRadarAPI and there is no more who was banned by using FlightRadarAPI client or this integration

**Comment by ginlik1996** [comment]
> > Are you still facing this issue? I'm looking forward to adding this integration to my HA, but I don't want my IP to be banned. Thanks!
> 
> Hi, yes absolutely I’m still in contact with support about trying to get unbanned, latest update is that “unfortunately you accepted the terms and conditions of our service (FR24) so the ban was correctly administered”. It’s a great integration but this whole IP banning thing isn’t great. I’ll update if I manage to get them to unblock me.

This is not a great behaviour. Almost always, at least here in Italy, residential connection have dynamic, and sometimes shared, public IPs, so the ban would last only for some day/week.

How did you set up the integration (radius, scan interval and if you added your FR24 account)?

**Comment by sammckenzie236** [comment]
> > > Are you still facing this issue? I'm looking forward to adding this integration to my HA, but I don't want my IP to be banned. Thanks!
> > 
> > 
> > Hi, yes absolutely I’m still in contact with support about trying to get unbanned, latest update is that “unfortunately you accepted the terms and conditions of our service (FR24) so the ban was correctly administered”. It’s a great integration but this whole IP banning thing isn’t great. I’ll update if I manage to get them to unblock me.
> 
> This is not a great behaviour. Almost always, at least here in Italy, residential connection have dynamic, and sometimes shared, public IPs, so the ban would last only for some day/week.
> 
> How did you set up the integration (radius, scan interval and if you added your FR24 account)?

From memory (I removed the integration) I was scanning every 30 seconds, and I’m pretty sure I didn’t add my Flightradar24 account. Radius was about +- 30km.

Regarding the IP, I live in Australia and used to be under CG-NAT meaning I shared an IP with other connections but I had that removed as I needed to run some services locally and needed outside access. I don’t pay for a static IP but I find my ISP hasn’t changed my IP since I opted out of CG-NAT. I could try getting them to change it to resolve the ban but that’s a bit of a hacky way out and my (few) servers would have to be reconfigured.

**Comment by AlexandrErohin** [comment]
@sammckenzie236 30km - it is a lot. How many flights was detected in your area?

**Comment by sammckenzie236** [comment]
@AlexandrErohin no more than 15 at a time on a nice day, mostly GA traffic from a nearby GA airport. I get the occasional commercial going almost overhead as I live under that path but that usually only happens every hour or so.

**Comment by AlexandrErohin** [comment]
@sammckenzie236 It looks like you have a lot flights in your area in total per day. And plus you have other devices which sends requests to FR24
