### ISSUE TITLE
Added to track disappears. 

### ISSUE THREAD

**Issue by ronbruins** [AlexandrErohin/home-assistant-flightradar24#47]
When I add a flight to track, after some time it disappears from the sensor. Is there a certain logic that causes this? I want to track a scheduled flight and notify me when there's an update.

**Comment by Manbearpig92** [comment]
Yeah same. I added my flight 2 hours before departure and it disappeared when I got on the plane. Had to re add it before take off

**Comment by swampylee** [comment]
Same here, I would like to be able to continually track a couple of scheduled flights without them being removed from the list.

**Comment by AlexandrErohin** [comment]
@ronbruins @Manbearpig92 @swampylee Fixed. Please try the latest version
P.S. Dont forget please to give a star to the repo :)

**Comment by swampylee** [comment]
> @ronbruins @Manbearpig92 @swampylee Fixed. Please try the latest version P.S. Dont forget please to give a star to the repo :)

Thanks! Just trying it now.

**Comment by swampylee** [comment]
> > @ronbruins @Manbearpig92 @swampylee Fixed. Please try the latest version P.S. Dont forget please to give a star to the repo :)
> 
> Thanks! Just trying it now.

Works great except on restart of HA it loses the tracked flights, any way to keep them?

**Comment by ronbruins** [comment]
I finally was able to actually test this. Added the flight yesterday and it showed scheduled. Now it just departed and it beautifully displays the details in my dashboard. 

![image](https://github.com/user-attachments/assets/574167e2-9e83-4e5b-b04d-0ecf1943c88f)

https://github.com/user-attachments/assets/d8fbb63e-ca9e-4647-9d4d-27aef079f2f2
