### ISSUE TITLE
Feature request: Add date to Addtional Tracked Flights

### ISSUE THREAD

**Issue by stejo388** [AlexandrErohin/home-assistant-flightradar24#60]
Hi, 

I would be great if it would be possible to a also add a date to the additional tracked flights. I use it to add flights I do during business trips so my family could follow the flights on our info displays.

To make it more easy I could add the flights I should do before together with a date and then I could show only the specific flight I will fly.

**Comment by AlexandrErohin** [comment]
You may create an automation - that add your flight at a proper date. Also in this automation you may add notifications and other things

It would be more complex to add a flight if requires more data than callsign. I think it is better to keep it simple so it would be easy to use for everyone.
