### ISSUE TITLE
Bug?: event flightradar24_tracked_took_off and flightradar24_tracked_landed dont work

### ISSUE THREAD

**Issue by ohuc** [AlexandrErohin/home-assistant-flightradar24#65]
`flightradar24_tracked_landed` and
`flightradar24_tracked_took_off` 

both of these events dont seem to work accurately they work sometimes but most of the times they don't fire any event.

**Comment by AlexandrErohin** [comment]
Since this is the only message about such an error - please provide more information to understand how this error is reproduced and in what cases. There are a lot people who use this integration - Has someone encountered this error too? Unfortunately, I can't reproduce it

**Comment by AlexandrErohin** [comment]
@ohuc Could you try the newest version v1.20.2 and let me know?

**Comment by ohuc** [comment]
> @ohuc Could you try the newest version v1.20.2 and let me know?

seems to work perfectly now! thanks

**Comment by AlexandrErohin** [comment]
@ohuc Dont forget please to give a star to the repo :)

**Comment by ohuc** [comment]
Hey it looks like it fails to fire an event during landing frequently

**Comment by AlexandrErohin** [comment]
@ohuc have you changed - The minimum and maximum altitudes in foots between which the aircraft will be tracked ?

**Comment by AlexandrErohin** [comment]
@ohuc Please try v1.23.0. I have tested it and no problem found with events

**Comment by ohuc** [comment]
Works perfectly now thank you :)
