### ISSUE TITLE
Cannot input 0 in decimal for lat/lon

### ISSUE THREAD

**Issue by Hood-fr** [AlexandrErohin/home-assistant-flightradar24#66]
When defining the latitude/longitude for the area, the "0" character cannot be typed in the decimal part

Example : Try to type in "42.701" as latitude, you would end up with "42.71". As it is, you need to go back to insert the 0 between the 7 and the 1

**Comment by AlexandrErohin** [comment]
Hi. 
It is a frontend bug. You may try to setup coordinates in Meteorologisk institutt (Met.no) integration. Same problem with 0.
You may open an issue here https://github.com/home-assistant/frontend
