### ISSUE TITLE
I don't understand the content of sensor.flightradar24_entered_area

### ISSUE THREAD

**Issue by Hood-fr** [AlexandrErohin/home-assistant-flightradar24#69]
Hello,

I have a 25km zone centered over Marseille, southern France. 
It is working fine as I am using sensor.flightradar24_current_in_area data without any issue.

But I have a hard time trying to understand the other sensor flightradar24_entered_area
Here is a log of the data defined in the flight attribute of the sensor :

Eurofighter Typhoon FGR.4 | RAMPAG33 |   | Coningsby |   | QCY |  
Airbus A320-232 | MEA313 | ME313 | Amman | Beirut | AMM | BEY
Airbus A380-861 | UAE9H | EK28 | Glasgow | Dubai | GLA | DXB
Airbus A320-232 | ISR256 | 6H256 | Berlin | Tel Aviv | BER | TLV
Boeing 737-958(ER) | ELY543 | LY543 | Tel Aviv | Athens | TLV | ATH
ATR 72-600 | IRA3417 | IR3417 | Tehran | Dezful | THR | DEF
Boeing CH-47F Chinook | EASY44 |   | Szeged |   | QHD |  
ATR 72-600 | IRA3417 | IR3417 | Tehran | Dezful | THR | DEF
Airbus A320-232 | ISR562 | 6H562 | Athens | Tel Aviv | ATH | TLV
Airbus A320-231 | AIZ151 | IZ151 | Tel Aviv | Pafos | TLV | PFO
Airbus A380-861 | UAE87Q | EK88 | Zurich | Dubai | ZRH | DXB
Airbus A320-232 | ISR562 | 6H562 | Athens | Tel Aviv | ATH | TLV
Boeing 747-467F | AZG391 | 7L391 | Baku | Birmingham | GYD | BHX
Airbus A380-861 | UAE87Q | EK88 | Zurich | Dubai | ZRH | DXB
Boeing 737-8HX | ELY2367 | LY2367 | Tel Aviv | Budapest | TLV | BUD
Airbus A380-861 | UAE87Q | EK88 | Zurich | Dubai | ZRH | DXB
Embraer E190LR | SLI2740 | AM2740 | Mexico City | Tampa | MEX | TPA

You'll easily note that none of these flights came close to Marseille at any point. What did I do wrong ?

Thanks for your support

**Comment by AlexandrErohin** [comment]
If you entered 25000 - you entered zone with 25km radius - so you have 50km of diameter.
sensor.flightradar24_entered_area - shows the data of a flight that has entered your zone of 50km

**Comment by Hood-fr** [comment]
That's what I expected, but I really doubt that a flight between Mexico City and Tampa, FL flew within 25km of Marseille, France

**Comment by Hood-fr** [comment]
Solved : the "most tracked flights" option was activated in the zone configuration. I let you check if the output of that sensor is a bug or not
