### ISSUE TITLE
Is there any way to remove the apple images to get more screen realistate?

### ISSUE THREAD

**Issue by tconnz** [AlexandrErohin/home-assistant-flightradar24#76]
Hi there,

With a subscription, is there any known / acceptable way to remove the two fairly large Apple and Google Play images in the bottom right of the map iframe?

I've entered in my subscription details into the config hoping it would remove ads like it does on the main Flightradar24 web page, but to no avail.

Cheers!

**Comment by PV-Joe** [comment]
Yes there is a solution for this at the home assistant community forum:

https://community.home-assistant.io/t/custom-component-flightradar24/641969/172?u=pv-joe

Hope this helps!

**Comment by AlexandrErohin** [comment]
Would be great if you give a star to the repo :) Thanks!
