### ISSUE TITLE
Problem with manual installation of integration

### ISSUE THREAD

**Issue by halldark** [AlexandrErohin/home-assistant-flightradar24#79]
Home Assistant
Core
2024.10.3
Frontend
20241002.3

as well observed in September release.
installation as in https://github.com/AlexandrErohin/home-assistant-flightradar24#manual
custom_components/flightradar24 (v.1.22.0) in /config/custom_components (restart done)

add integration via gui ends with: Error
Config flow could not be loaded: {"message":"Invalid handler specified"}

error in logs: Logger: homeassistant.config_entries
Source: config_entries.py:2945
First occurred: 9:36:01 AM (7 occurrences)
Last logged: 10:33:04 AM

Error occurred loading flow for integration flightradar24: No module named 'FlightRadar24'

**Comment by AlexandrErohin** [comment]
Final directory should be /config/custom_components/flightradar24 and then should be restarted HA

Best way is install it via HACS

**Comment by halldark** [comment]
Thank you for coming back. Sorry I think was not explicit with my explanation. Files of integration are as advice (as for usual addons): in this case /config/custom_components/flightradar24. I will consider installation of HACS in my core container, so far I was not required for other integrations which I use.

**Comment by mrboogiee** [comment]
same here, just tried a fresh install on my environment from HACS and ran into the same error message:

`Config flow could not be loaded: {"message":"Invalid handler specified"}`

addon version: v1.22.0
core version: 2024.10.4
frontend version: 20241002.4

Logs:
```
Logger: homeassistant.config_entries
Source: config_entries.py:2945
First occurred: 14:26:11 (1 occurrences)
Last logged: 14:26:11

Error occurred loading flow for integration flightradar24: No module named 'FlightRadar24'
```

location on disk: /config/custom_components/flightradar24

**Comment by AlexandrErohin** [comment]
There is an topic may help https://community.home-assistant.io/t/hacs-installing-problem-via-integration-error-config-flow-could-not-be-loaded/314501/17
