### ISSUE TITLE
Strange behaviour

### ISSUE THREAD

**Issue by mfabiani53** [AlexandrErohin/home-assistant-flightradar24#82]
I am getting strange behaviour with this integration and the related frontend card.
Everytime i try to open and view the dashboard with this integration i am forced to delete cache… only after 2 or 3 times i clear the cache the page shows itself, otherwise i have only a blank page.
Any other has the same behaviour?

**Comment by AlexandrErohin** [comment]
Im closing this, as nobody had this too. It looks like it is something with A frontend. It is not related to this integration
