### ISSUE TITLE
Feature request: Scheduled Tracked flights

### ISSUE THREAD

**Issue by mukowman** [AlexandrErohin/home-assistant-flightradar24#84]
I love this integration helps me see when my partner is flying.
I often add tracked flights on the day they are flying so as to not track flights they are not on with the same name the day before.
I would love to see a feature where you can schedule the day to add the tracked flight on and remove.

**Comment by AlexandrErohin** [comment]
You may always use Home assistant automation feature - where you may write any schedule you want and add there or delete  flights https://github.com/AlexandrErohin/home-assistant-flightradar24?tab=readme-ov-file#automation
P.S. Would be great if you could give a star to the repo :) Thanks

**Comment by mukowman** [comment]
Of course, repo starred now.
I had a look at using the automation logic within Home Assistant for my use case but started to get a little complex.
Essentially, I needed a way to store the date and flight number for multiple flights, so I was using a script to add a comma separated array to a text helper to store multiple flights and dates.

The automation would consist of each day checking this helper and extracting any flights occurring today, then add them to tracking and also check if any flights were in the past and remove them from the list and the tracker.

I may revisit this automation again when I have some time.
