### ISSUE TITLE
Device tracker configuration

### ISSUE THREAD

**Issue by amastrogiacomo1968** [AlexandrErohin/home-assistant-flightradar24#85]
I would like to configure the device tracker for a flight but the link to configure (https://github.com/AlexandrErohin/home-assistant-flightradar24/blob/main/edit-configuration) is incorrect

**Comment by AlexandrErohin** [comment]
@amastrogiacomo1968 Would be great if you could give a star to the repo :) Thanks

**Comment by amastrogiacomo1968** [comment]
Done :-)
