### ISSUE TITLE
Possible simplification by using get_bounds_by_point

### ISSUE THREAD

**Issue by sj3fk3** [AlexandrErohin/home-assistant-flightradar24#9]
Not completely sure, but it looks like the integration also does a calculation to find the bounding box, based on coordinates and radius, but the pyton FlightRadarAPI also has a call for that? `get_bounds_by_point`.

Maybe that was not used for a reason, or maybe it was overlooked?

**Comment by AlexandrErohin** [comment]
get_bounds_by_point - it was my contribution to FlightRadarAPI. I added it to FlightRadarAPI after that I published this component
