### ISSUE TITLE
Real departure and Arrival times stays null after a flight has taken off

### ISSUE THREAD

**Issue by kaizersoje** [AlexandrErohin/home-assistant-flightradar24#90]
I have noticed that the `time_real_departure` and `time_real_arrival` values show up as `null` after a flight has taken off. I can see the ATD and ETA shows the time in the FlightRadar24 website for the flight.

This is an example 

![image](https://github.com/user-attachments/assets/78471f0c-d0fd-49e6-bc40-158ef5c27a86)
![image](https://github.com/user-attachments/assets/16716412-cc89-4ce0-beb3-87d1d1017f65)

**Comment by AlexandrErohin** [comment]
@kaizersoje I have added additional update after take off - Please try v1.23.0
P.S. Would be great if you could give a star to the repo :) Thanks
