### ISSUE TITLE
Map not allowed to show

### ISSUE THREAD

**Issue by RaxCore** [AlexandrErohin/home-assistant-flightradar24#92]
Hi,
I tried to include the map using this link: https://www.flightradar24.com/52.37,13.53/12
Unfortunately the preview says that for security reasons firefox isn´t allowed to show this site embedded in another site.
<img width="386" alt="Übersicht – Home Assistant – Mozilla Firefox_2024-12-19 13_42_07" src="https://github.com/user-attachments/assets/d1b6231f-35ec-4ce9-857b-4d3f100bd76f" />

**Comment by RaxCore** [comment]
**Solved.** 
You must not use a standalone iframe / website-card. It seems that the iframe has to be integrated into the code of the vertical stack, just like the demo code.

**Comment by AlexandrErohin** [comment]
@RaxCore Would be great if you could give a star to the repo :) Thanks
